# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db028be15164ba112964e4543a957c317b3d0ec670b394810ddddd8fcc27723ed79d12293c3f85d5e1dac4b47dea394a972c551c2799587325aad6437d359ab1

test:
  secret_key_base: 54debc7ad8fcc30d7685bf861f97c8a150f7e79360f1d1a74bc1edff111944cd5fc1c23d7b8dae0bcc866160b7d30afa0499528b83f984d9a28565dbb25f4c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
